(function() {var implementors = {};
implementors["sos_kernel"] = ["impl&lt;'a, T&gt; <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/ops/place/trait.Placer.html\" title=\"trait core::ops::place::Placer\">Placer</a>&lt;T&gt; for <a class=\"struct\" href=\"alloc/vec/struct.PlaceBack.html\" title=\"struct alloc::vec::PlaceBack\">PlaceBack</a>&lt;'a, T&gt;","impl&lt;'a, T&gt; <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/ops/place/trait.Placer.html\" title=\"trait core::ops::place::Placer\">Placer</a>&lt;T&gt; for <a class=\"struct\" href=\"alloc/linked_list/struct.FrontPlace.html\" title=\"struct alloc::linked_list::FrontPlace\">FrontPlace</a>&lt;'a, T&gt;","impl&lt;T&gt; <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/ops/place/trait.Placer.html\" title=\"trait core::ops::place::Placer\">Placer</a>&lt;T&gt; for <a class=\"struct\" href=\"alloc/boxed/struct.ExchangeHeapSingleton.html\" title=\"struct alloc::boxed::ExchangeHeapSingleton\">ExchangeHeapSingleton</a>","impl&lt;'a, T&gt; <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/ops/place/trait.Placer.html\" title=\"trait core::ops::place::Placer\">Placer</a>&lt;T&gt; for <a class=\"struct\" href=\"alloc/vec_deque/struct.PlaceFront.html\" title=\"struct alloc::vec_deque::PlaceFront\">PlaceFront</a>&lt;'a, T&gt;","impl&lt;'a, T&gt; <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/ops/place/trait.Placer.html\" title=\"trait core::ops::place::Placer\">Placer</a>&lt;T&gt; for <a class=\"struct\" href=\"alloc/linked_list/struct.BackPlace.html\" title=\"struct alloc::linked_list::BackPlace\">BackPlace</a>&lt;'a, T&gt;","impl&lt;'a, T&gt; <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/ops/place/trait.Placer.html\" title=\"trait core::ops::place::Placer\">Placer</a>&lt;T&gt; for <a class=\"struct\" href=\"alloc/vec_deque/struct.PlaceBack.html\" title=\"struct alloc::vec_deque::PlaceBack\">PlaceBack</a>&lt;'a, T&gt;","impl&lt;'a, T&gt; <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/ops/place/trait.Placer.html\" title=\"trait core::ops::place::Placer\">Placer</a>&lt;T&gt; for &amp;'a mut <a class=\"struct\" href=\"alloc/binary_heap/struct.BinaryHeap.html\" title=\"struct alloc::binary_heap::BinaryHeap\">BinaryHeap</a>&lt;T&gt; <span class=\"where fmt-newline\">where<br>&nbsp;&nbsp;&nbsp;&nbsp;T: 'a + <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/clone/trait.Clone.html\" title=\"trait core::clone::Clone\">Clone</a> + <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/cmp/trait.Ord.html\" title=\"trait core::cmp::Ord\">Ord</a>,&nbsp;</span>",];

            if (window.register_implementors) {
                window.register_implementors(implementors);
            } else {
                window.pending_implementors = implementors;
            }
        
})()
