(function() {var implementors = {};
implementors["alloc"] = ["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/convert/trait.Into.html\" title=\"trait core::convert::Into\">Into</a>&lt;usize&gt; for <a class=\"struct\" href=\"memory/struct.VAddr.html\" title=\"struct memory::VAddr\">VAddr</a>","impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/convert/trait.Into.html\" title=\"trait core::convert::Into\">Into</a>&lt;u64&gt; for <a class=\"struct\" href=\"memory/arch/x86_64/struct.PAddr.html\" title=\"struct memory::arch::x86_64::PAddr\">PAddr</a>","impl&lt;'a, W&gt; <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/convert/trait.Into.html\" title=\"trait core::convert::Into\">Into</a>&lt;<a class=\"struct\" href=\"https://doc.rust-lang.org/nightly/core/ops/struct.Range.html\" title=\"struct core::ops::Range\">Range</a>&lt;<a class=\"struct\" href=\"memory/arch/x86_64/struct.PhysicalPage.html\" title=\"struct memory::arch::x86_64::PhysicalPage\">PhysicalPage</a>&gt;&gt; for &amp;'a (<a class=\"trait\" href=\"elf/section/trait.Header.html\" title=\"trait elf::section::Header\">Header</a>&lt;Word = W&gt; + 'static) <span class=\"where fmt-newline\">where<br>&nbsp;&nbsp;&nbsp;&nbsp;W: <a class=\"trait\" href=\"elf/trait.ElfWord.html\" title=\"trait elf::ElfWord\">ElfWord</a>,&nbsp;</span>",];
implementors["arrayvec"] = [];
implementors["elf"] = ["impl&lt;'a, W:&nbsp;<a class=\"trait\" href=\"elf/trait.ElfWord.html\" title=\"trait elf::ElfWord\">ElfWord</a>&gt; <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/convert/trait.Into.html\" title=\"trait core::convert::Into\">Into</a>&lt;<a class=\"type\" href=\"memory/type.FrameRange.html\" title=\"type memory::FrameRange\">FrameRange</a>&gt; for &amp;'a <a class=\"type\" href=\"elf/type.Section.html\" title=\"type elf::Section\">Section</a>&lt;W&gt;",];
implementors["memory"] = ["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/convert/trait.Into.html\" title=\"trait core::convert::Into\">Into</a>&lt;u64&gt; for <a class=\"struct\" href=\"memory/struct.PAddr.html\" title=\"struct memory::PAddr\">PAddr</a>","impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/convert/trait.Into.html\" title=\"trait core::convert::Into\">Into</a>&lt;usize&gt; for <a class=\"struct\" href=\"memory/struct.VAddr.html\" title=\"struct memory::VAddr\">VAddr</a>",];
implementors["paging"] = ["impl&lt;'a, W&gt; <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/convert/trait.Into.html\" title=\"trait core::convert::Into\">Into</a>&lt;<a class=\"struct\" href=\"https://doc.rust-lang.org/nightly/core/ops/range/struct.Range.html\" title=\"struct core::ops::range::Range\">Range</a>&lt;<a class=\"struct\" href=\"memory/arch/x86_64/struct.PhysicalPage.html\" title=\"struct memory::arch::x86_64::PhysicalPage\">PhysicalPage</a>&gt;&gt; for &amp;'a (<a class=\"trait\" href=\"elf/section/trait.Header.html\" title=\"trait elf::section::Header\">Header</a>&lt;Word = W&gt; + 'static) <span class=\"where fmt-newline\">where<br>&nbsp;&nbsp;&nbsp;&nbsp;W: <a class=\"trait\" href=\"elf/trait.ElfWord.html\" title=\"trait elf::ElfWord\">ElfWord</a>,&nbsp;</span>","impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/convert/trait.Into.html\" title=\"trait core::convert::Into\">Into</a>&lt;usize&gt; for <a class=\"struct\" href=\"memory/struct.VAddr.html\" title=\"struct memory::VAddr\">VAddr</a>","impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/convert/trait.Into.html\" title=\"trait core::convert::Into\">Into</a>&lt;u64&gt; for <a class=\"struct\" href=\"memory/arch/x86_64/struct.PAddr.html\" title=\"struct memory::arch::x86_64::PAddr\">PAddr</a>",];
implementors["sos_alloc"] = ["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/convert/trait.Into.html\" title=\"trait core::convert::Into\">Into</a>&lt;usize&gt; for <a class=\"struct\" href=\"memory/struct.VAddr.html\" title=\"struct memory::VAddr\">VAddr</a>","impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/convert/trait.Into.html\" title=\"trait core::convert::Into\">Into</a>&lt;u64&gt; for <a class=\"struct\" href=\"memory/arch/x86_64/struct.PAddr.html\" title=\"struct memory::arch::x86_64::PAddr\">PAddr</a>","impl&lt;'a, W&gt; <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/convert/trait.Into.html\" title=\"trait core::convert::Into\">Into</a>&lt;<a class=\"struct\" href=\"https://doc.rust-lang.org/nightly/core/ops/range/struct.Range.html\" title=\"struct core::ops::range::Range\">Range</a>&lt;<a class=\"struct\" href=\"memory/arch/x86_64/struct.PhysicalPage.html\" title=\"struct memory::arch::x86_64::PhysicalPage\">PhysicalPage</a>&gt;&gt; for &amp;'a (<a class=\"trait\" href=\"elf/section/trait.Header.html\" title=\"trait elf::section::Header\">Header</a>&lt;Word = W&gt; + 'static) <span class=\"where fmt-newline\">where<br>&nbsp;&nbsp;&nbsp;&nbsp;W: <a class=\"trait\" href=\"elf/trait.ElfWord.html\" title=\"trait elf::ElfWord\">ElfWord</a>,&nbsp;</span>",];
implementors["sos_kernel"] = ["impl&lt;'a, W&gt; <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/convert/trait.Into.html\" title=\"trait core::convert::Into\">Into</a>&lt;<a class=\"struct\" href=\"https://doc.rust-lang.org/nightly/core/ops/range/struct.Range.html\" title=\"struct core::ops::range::Range\">Range</a>&lt;<a class=\"struct\" href=\"memory/arch/x86_64/struct.PhysicalPage.html\" title=\"struct memory::arch::x86_64::PhysicalPage\">PhysicalPage</a>&gt;&gt; for &amp;'a (<a class=\"trait\" href=\"elf/section/trait.Header.html\" title=\"trait elf::section::Header\">Header</a>&lt;Word = W&gt; + 'static) <span class=\"where fmt-newline\">where<br>&nbsp;&nbsp;&nbsp;&nbsp;W: <a class=\"trait\" href=\"elf/trait.ElfWord.html\" title=\"trait elf::ElfWord\">ElfWord</a>,&nbsp;</span>","impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/convert/trait.Into.html\" title=\"trait core::convert::Into\">Into</a>&lt;usize&gt; for <a class=\"struct\" href=\"memory/struct.VAddr.html\" title=\"struct memory::VAddr\">VAddr</a>","impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/convert/trait.Into.html\" title=\"trait core::convert::Into\">Into</a>&lt;u64&gt; for <a class=\"struct\" href=\"memory/arch/x86_64/struct.PAddr.html\" title=\"struct memory::arch::x86_64::PAddr\">PAddr</a>","impl&lt;T&gt; <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/convert/trait.Into.html\" title=\"trait core::convert::Into\">Into</a>&lt;<a class=\"struct\" href=\"alloc/boxed/struct.Box.html\" title=\"struct alloc::boxed::Box\">Box</a>&lt;[T]&gt;&gt; for <a class=\"struct\" href=\"alloc/vec/struct.Vec.html\" title=\"struct alloc::vec::Vec\">Vec</a>&lt;T&gt;","impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/convert/trait.Into.html\" title=\"trait core::convert::Into\">Into</a>&lt;<a class=\"struct\" href=\"alloc/boxed/struct.Box.html\" title=\"struct alloc::boxed::Box\">Box</a>&lt;str&gt;&gt; for <a class=\"struct\" href=\"alloc/string/struct.String.html\" title=\"struct alloc::string::String\">String</a>","impl&lt;'a&gt; <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/convert/trait.Into.html\" title=\"trait core::convert::Into\">Into</a>&lt;<a class=\"struct\" href=\"params/mem/struct.Area.html\" title=\"struct params::mem::Area\">Area</a>&gt; for &amp;'a <a class=\"struct\" href=\"sos_kernel/arch/multiboot2/struct.MemArea.html\" title=\"struct sos_kernel::arch::multiboot2::MemArea\">MemArea</a>",];

            if (window.register_implementors) {
                window.register_implementors(implementors);
            } else {
                window.pending_implementors = implementors;
            }
        
})()
